#Quiz

city = input("What is the capital city of France?")

if city == "Paris" or city == "paris":
    print("Correct")
else:
    print("Incorrect")

number_of_times = int(input("How many times have England won the world cup?"))

if number_of_times == 1:
    print("Correct")

else:
    print("Incorrect")

city = input("What is the capital city of Spain?")

if city == "Madrid" or city == "madrid":
    print("Correct")
else:
    print("Incorrect")
    
